import Head from 'next/head'
import Image from 'next/image'
import { Inter } from 'next/font/google'
import Form from '@/components/OrderForm'
import ClucksteinForm from '@/components/ClucksteinForm'
import Link from 'next/link'

const inter = Inter({ subsets: ['latin'] })

export default function Home() {



  return (
    <>
      <Head>
        <title>NYU EATZ</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <h1>
        Welcome to NYU Eatz!
      </h1>
      <div className='home-panel'>
        <p>If you want to sell your extra meal swipes, check out a list of <Link href="/sell">unfulfilled orders</Link></p>
      </div>
      <div className='home-panel'>
      <p>If you want to buy discounted meals, check out our current <Link href="/buy">menu</Link></p>
      </div>
      
    </>
  )
}
