import Head from 'next/head'
import Image from 'next/image'
import { Inter } from 'next/font/google'
import Form from '@/components/OrderForm'
import ClucksteinForm from '@/components/ClucksteinForm'
import Link from 'next/link'

const inter = Inter({ subsets: ['latin'] })

export default function Home() {



  return (
    <>
      <Head>
        <title>NYU EATZ</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Link href="/buy">Buy Discounted Meals</Link>
      <Link href="/sell">Sell Meal Swipes</Link>
    </>
  )
}
